- name: "OpenLDAP directory server config specific to Perun"
  import_tasks: perun_ldap_config.yml
  when: perun_ldap_local
  tags:
    - perun_ldap_config


- name: "LDAP DS389 directory server config specific to Perun"
  import_tasks: perun_ldap_ds389_config.yml
  when: perun_ldap_ds389_local 
  tags:
     - perun_ldap_ds389_config      
