- name: "OpenLDAP directory server config specific to Perun"
  when: perun_ldap_implementation=="openldap"
  include_tasks:
    file: perun_openldap_config.yml
    apply:
      tags:
        - perun_ldap_config
  tags:
    - perun_ldap_config

- name: "LDAP DS389 directory server config specific to Perun"
  when: perun_ldap_implementation=="ds389"
  include_tasks:
    file: perun_ds389_config.yml
    apply:
      tags:
        - perun_ldap_config
  tags:
     - perun_ldap_config
