- assert:
    that:
      - perun_ldap_schemas_perun_version is defined
      - perun_ldap_access_rules_additional is defined
      - perun_ldap_basedn is defined

- name: "set cn=config attribute olcAttributeOptions: x-ns-"
  ldap_attrs:
    dn: cn=config
    attributes:
      olcAttributeOptions: "x-ns-"
    state: present

- name: "create perun-specific LDAP schemas"
  when: not perun_ldap_slave_replica
  block:
    - name: "create entry for schema perun"
      ldap_entry:
        dn: cn={4}perun,cn=schema,cn=config
        objectClass: olcSchemaConfig
      register: perun_schema_entry
    - name: "download schema perun file version {{ perun_ldap_schemas_perun_version }}"
      get_url:
        url: "https://gitlab.ics.muni.cz/perun/perun-idm/perun/-/raw/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/perun-schema.ldif"
        dest: "/etc/ldap/perun-schema.ldif"
        force: yes
      register: perun_schema_file
    - name: "set up schema perun"
      command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/perun-schema.ldif"
      when: perun_schema_entry.changed or perun_schema_file.changed

    - name: "create entry for schema inetUser"
      ldap_entry:
        dn: cn={5}inetUser,cn=schema,cn=config
        objectClass: olcSchemaConfig
      register: inetUser_schema_entry
    - name: "download schema inetUser file version {{ perun_ldap_schemas_perun_version }}"
      get_url:
        url: "https://gitlab.ics.muni.cz/perun/perun-idm/perun/-/raw/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/inetUser-schema.ldif"
        dest: "/etc/ldap/inetUser-schema.ldif"
        force: yes
      register: inetUser_schema_file
    - name: "set up schema inetUser"
      command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/inetUser-schema.ldif"
      when: inetUser_schema_entry.changed or inetUser_schema_file.changed

    - name: "create entry for schema tenOperEntry"
      ldap_entry:
        dn: cn={6}tenOperEntry,cn=schema,cn=config
        objectClass: olcSchemaConfig
      register: tenOperEntry_schema_entry
    - name: "download schema tenOperEntry file version {{ perun_ldap_schemas_perun_version }}"
      get_url:
        url: "https://gitlab.ics.muni.cz/perun/perun-idm/perun/-/raw/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/tenOperEntry-schema.ldif"
        dest: "/etc/ldap/tenOperEntry-schema.ldif"
        force: yes
      register: tenOperEntry_schema_file
    - name: "set up schema tenOperEntry"
      command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/tenOperEntry-schema.ldif"
      when: tenOperEntry_schema_entry.changed or tenOperEntry_schema_file.changed

- name: "set indexes (olcDbIndex attribute)"
  ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcDbIndex:
        - cn,uid eq
        - member,memberUid eq
        - objectClass eq
        - uidNumber,gidNumber eq
        - perunVoId eq
        - eduPersonPrincipalNames eq
        - entryCSN,entryUUID eq
        - login eq
        - memberOfPerunVo eq
        - userCertificateSubject eq
        - entityID eq
        - assignedToResourceId eq
        - userIdentities eq
        - OIDCClientID eq
        - perunFacilityId eq
        - perunFacilityDn eq
        - perunUserId eq
        - perunGroupId eq
        - assignedGroupId eq
        - internalUserIdentifiers eq
    state: exact

- name: "LDAP access rules"
  tags: ldap_acl
  block:
    - name: "LDAP access rules empty"
      set_fact:
        olcAccess_values: []
        oldAccess_replication:
          - >-
            to dn.subtree="{{ perun_ldap_basedn }}"
            by dn.exact="cn=replication,{{ perun_ldap_basedn }}" read
            by * break
    - name: "LDAP access rule for replication must be first"
      when: perun_ldap_master_replica
      set_fact:
        olcAccess_values: "{{ olcAccess_values + oldAccess_replication }}"
    - name: "LDAP access rules start"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + perun_ldap_access_rules_start }}"
    - name: "additional LDAP access rules"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + perun_ldap_access_rules_additional }}"
    - name: "LDAP access rules end"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + perun_ldap_access_rules_end }}"
    - name: "modify OpenLDAP access rights"
      ldap_attrs:
        dn: olcDatabase={1}mdb,cn=config
        attributes:
          olcAccess: "{{ olcAccess_values }}"
        ordered: yes
        state: exact

- name: "cron job for backup of second LDAP branch with hostel passwords"
  when: perun_ldap_backup_hostel
  cron:
    name: "Everyday do backup of the LDAP hostel branch"
    cron_file: ldap-backup
    hour: "{{ perun_ldap_daily_backup_hour | string }}"
    minute: "{{ perun_ldap_daily_backup_minute | string }}"
    user: root
    job: "umask 027 ; rm /etc/ldap/ldap_db_2_backup.ldif ; /usr/sbin/slapcat -n 2 -l /etc/ldap/ldap_db_2_backup.ldif"

- name: "get OS service facts"
  when: ansible_facts.services['slapd'] is not defined
  service_facts:

- name: "set up limits for max open files for instance and display it"
  when: perun_ldap_max_open_files_limits
  block:
    - name: "set soft open file limit for openldap user"
      community.general.pam_limits:
        domain: openldap
        limit_type: soft
        limit_item: nofile
        value: "{{ perun_ldap_max_open_soft_files_user_ldap_value }}"
      register: soft_limit

    - name: "set hard open file limit for openldap user"
      community.general.pam_limits:
        domain: openldap
        limit_type: hard
        limit_item: nofile
        value: "{{ perun_ldap_max_open_hard_files_user_ldap_value }}"
      register: hard_limit

    - name: "set system-wide open files limit"
      ansible.posix.sysctl:
        name: fs.file-max
        value: "{{ perun_ldap_max_open_system_files_value }}"
      register: fs_file_max

    - name: "create systemd override config directory if it does not exist"
      ansible.builtin.file:
        path: /etc/systemd/system/slapd.service.d
        state: directory
        mode: '0755'

    - name: "add LimitNOFILE to systemd override configuration for slapd"
      blockinfile:
        path: /etc/systemd/system/slapd.service.d/override.conf
        create: yes
        block: |
          [Service]
          LimitNOFILE="{{ perun_ldap_no_file_limit_value }}"
      register: ldap_nofile_limit
      
    - name: "reload systemd to apply override changes"
      when:  soft_limit.changed or hard_limit.changed or fs_file_max.changed or ldap_nofile_limit.changed
      ansible.builtin.systemd:
        daemon_reload: true
    
    - name: "restart slapd service to apply new limits"
      when: ldap_nofile_limit.changed
      ansible.builtin.service:
        name: slapd
        state: restarted

    - name: "get soft open file limit for openldap"
      ansible.builtin.command: 
        "grep '^openldap.*soft.*nofile' /etc/security/limits.conf"
      register: ulimit_soft_result
      when: soft_limit.changed

    - name: "get hard open file limit for openldap"
      ansible.builtin.command: 
        "grep '^openldap.*hard.*nofile' /etc/security/limits.conf"
      register: ulimit_hard_result
      when: hard_limit.changed

    - name: "get system max open files limit"
      ansible.builtin.command: 
        "sysctl fs.file-max"
      register: sysctl_result
      when: fs_file_max.changed

    - name: "get slapd LimitNOFILE setting"
      ansible.builtin.command: 
        "systemctl show -p LimitNOFILE slapd"

      register: limitnofile_result
      when: ldap_nofile_limit.changed

    - name: "display configured soft open file limit for openldap"
      when: soft_limit.changed
      debug:
        msg: "Configured soft open file limit for openldap: {{ ulimit_soft_result.stdout }}"

    - name: "display configured hard open file limit for openldap"
      when: hard_limit.changed
      debug:
        msg: "Configured hard open file limit for openldap: {{ ulimit_hard_result.stdout }}"

    - name: "display system max open files limit (fs.file-max)"
      when: fs_file_max.changed
      debug:
        msg: "System max open files limit (fs.file-max): {{ sysctl_result.stdout }}"

    - name: "display slapd LimitNOFILE setting"
      when: ldap_nofile_limit.changed
      debug:
        msg: "slapd LimitNOFILE setting: {{ limitnofile_result.stdout }}"

- name: "set up defaults limits for max open files for instance"
  when: not perun_ldap_max_open_files_limits
  block:
  - name: "remove soft and hard open file limits for openldap user"
    ansible.builtin.lineinfile:
      path: /etc/security/limits.conf
      state: absent
      regexp: '^openldap.*nofile'
    register: remove_hard_soft_limits

  - name: "reset system-wide open files limit to default"
    ansible.posix.sysctl:
      name: fs.file-max
      state: absent
    register: fs_file_max_default

  - name: "remove systemd override config directory for slapd"
    ansible.builtin.file:
      path: /etc/systemd/system/slapd.service.d/override.conf
      state: absent
    register: remove_conf

  - name: "remove systemd override directory if empty"
    when: remove_conf.changed
    ansible.builtin.file:
      path: /etc/systemd/system/slapd.service.d
      state: absent
    register: remove_slapd_dir

  - name: "reload systemd to apply override changes"
    when:  remove_hard_soft_limits.changed or fs_file_max_default.changed or remove_conf.changed
    ansible.builtin.systemd:
      daemon_reload: true
    
  - name: "restart slapd service to apply new limits"
    when: remove_conf.changed
    ansible.builtin.service:
      name: slapd
      state: restarted